// console.log("    |    |    ")
// console.log("    |    |    ")
// console.log("    |    |    ")
// console.log("--------------")
// console.log("    |    |    ")
// console.log("    |    |    ")
// console.log("    |    |    ")
// console.log("--------------")
// console.log("    |    |    ")
// console.log("    |    |    ")
// console.log("    |    |    ")

console.log("All Around The World".charAt(7).toUpperCase())
